# Generated by Django 5.2.2 on 2025-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeDeUmUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('nao-assistido', 'Não Assistido'), ('assistido', 'Assistido')], default='nao-assistido', max_length=15)),
                ('nota', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistiu_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
