# Generated by Django 5.2.2 on 2025-07-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeDeUmUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_id_api', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('nao-assistido', 'Não Assistido'), ('assistido', 'Assistido')], default='nao-assistido', max_length=15)),
                ('nota', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistiu_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'filme_id_api')},
            },
        ),
    ]
