# Generated by Django 5.2.3 on 2025-07-02 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeAssistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_id_api', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'filme_id_api')},
            },
        ),
        migrations.CreateModel(
            name='FilmeFavoritado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_id_api', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'filme_id_api')},
            },
        ),
        migrations.DeleteModel(
            name='FilmeDeUmUsuario',
        ),
    ]
