# Generated by Django 5.2.2 on 2025-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmedeumusuario',
            name='poster',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
